routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Models\User;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\FacebookController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[ProductController::class,'index'])->name('product');

Route::group(['middleware' => 'role:admin'], function() {
    Route::get('/admin/products',[AdminController::class,'products'])->middleware(['auth'])->name('admin.products');
    Route::get('/admin/categories',[AdminController::class,'categories'])->middleware(['auth'])->name('admin.categories');
    Route::resource('category',CategoryController::class )->except(['index','show']);
    Route::resource('product', ProductController::class)->except(['index','show']);

});


Route::resource('category',CategoryController::class )->only(['index','show']);
Route::resource('product', ProductController::class)->only(['index','show']);

Route::get('auth/google', [GoogleController::class, 'redirectToGoogle']);
Route::get('/gl/callback', [GoogleController::class, 'handleGoogleCallback']);

Route::get('auth/facebook', [FacebookController::class, 'facebookRedirect']);
Route::get('/fb/callback', [FacebookController::class, 'loginWithFacebook']);

Route::get('lang/{locale?}', function ($locale = null) {
    app()->setLocale($locale);
    session()->put('locale', $locale);
    return redirect()->back();
});

require __DIR__.'/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Log;

class Product extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $guarded = [
        '_method',
        '_token'
    ];

    protected $dates = ['deleted_at'];


    public function category(){

        return $this->belongsTo(Category::class);

    }

    public static function boot(){
        parent::boot();


        static::creating(function($item) {

            Log::info('Creating product call: '.$item);
        });


        static::created(function($item) {

            Log::info('Created product call: '.$item);

        });

        static::updating(function($item) {

            Log::info('Updating product call: '.$item);

        });

        static::updated(function($item) {

            Log::info('Updated product call: '.$item);

        });

        static::deleted(function($item) {

            Log::info('Deleted product call: '.$item);

        });


    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::paginate(10);

        return view('dashboard')->withProducts($products);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.product.create')->withCategories($this->get_categories());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {

        $request = $request->all();
        if ($request['img'] ?? false) {

            $request['img'] =  $request['img']->store('thumbnails');
        }

        Product::create($request);


        return redirect(route('admin.products'))->with('success', 'Your category has been created.');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('layouts.product.view')->withProduct($product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {



        return view('admin.product.edit')->withProduct($product)->withCategories($this->get_categories());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Product $product)
    {

       $request = $request->all();


       foreach ($request as $key => $value){
           if(isset($product->$key)){
               $product->$key = $value;
           }
       }


        if ($request['img'] ?? false) {

            $product['img'] =  $request['img']->store('thumbnails');
        }

        $product->save();


        return redirect(route('admin.products'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {

        $product->delete();

        return redirect(route('admin.products'));
    }

    public function get_categories(){
        $categories=Category::select('id','name')->get()->keyBy('id')->toArray();

        foreach ($categories as $key => $category){
            $categories[$key]=$category['name'];
        }
        return $categories;
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/product/create.blade.php
<x-app-layout>

    <style>
        input{
            width: 100%;
        }
    </style>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    {{__('app.create_pr')}}
                </div>
                {!! Form::open(['url' => route('product.store'),'method'=>'POST','files'=>true]) !!}
                <div class="p-6 bg-white border-b border-gray-200">
                    {!! Form::label('name', __('app.name')) !!}
                    {!! Form::text('name',old('name'),['class'=>'']) !!}
                    <x-error name="name"/>

                </div>
                <div class="p-6 bg-white border-b border-gray-200">
                    {!! Form::label('category_id', __('app.category')) !!}
                    {!! Form::select('category_id', $categories) !!}
                </div>

                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="flex-1">
                        {!! Form::label('ing', __('app.img')) !!}
                        {!! Form::file('img',['value'=> old('img')])  !!}
                        <x-error name="img"/>

                    </div>
                </div>
                <div class="p-6 bg-white border-b border-gray-200">
                    {!! Form::label('description', __('app.description')) !!}
                    {!! Form::text('description',old('description')) !!}
                    <x-error name="description"/>

                </div>

                <div class="p-6 bg-white border-b border-gray-200">
                    {!! Form::submit(__('app.save'),['class'=>'transition-colors duration-300 text-xs font-semibold bg-gray-200 hover:bg-gray-300 rounded-full py-2 px-8']) !!}
                </div>

                {!! Form::close() !!}
                <div class="p-6 bg-white border-b border-gray-200">
                    <a href="{{route('admin.products')}}" class="transition-colors duration-300 text-xs font-semibold bg-gray-200 hover:bg-gray-300 rounded-full py-2 px-8"> < {{__('app.back')}} </a>
                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/admin/product/edit.blade.php
<x-app-layout>

    <style>
        input{
            width: 100%;
        }
    </style>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    {{ __('app.edit_pr') }}
                </div>
                {!! Form::open(['url' => route('product.update',$product->id),'method'=>'PUT','files'=>true]) !!}
                <div class="p-6 bg-white border-b border-gray-200">
                     {!! Form::label('name',  __('app.name')) !!}
                     {!! Form::text('name',old('name',$product->name),['class'=>'']) !!}
                    <x-error name="name"/>

                </div>
                <div class="p-6 bg-white border-b border-gray-200">
                    {!! Form::label('category_id',  __('app.category')) !!}
                    {!! Form::select('category_id', $categories, $product->category_id) !!}
                </div>

                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="flex-1">
                        {!! Form::label('ing', __('app.img')) !!}
                        {!! Form::file('img',['value'=> old('img', $product->img)])  !!}
                        <x-error name="img"/>

                    </div>
                    <img src="{{ asset('storage/' . $product->img) }}" alt="{!! $product->img !!}" class="rounded-xl ml-6" width="100" />
                </div>
                <div class="p-6 bg-white border-b border-gray-200">
                    {!! Form::label('description',  __('app.description')) !!}
                    {!! Form::text('description',old('description',$product->description)) !!}
                    <x-error name="description"/>

                </div>

                <div class="p-6 bg-white border-b border-gray-200">
                    {!! Form::submit(__('app.save'),['class'=>'transition-colors duration-300 text-xs font-semibold bg-gray-200 hover:bg-gray-300 rounded-full py-2 px-8']) !!}
                </div>

                {!! Form::close() !!}
                <div class="p-6 bg-white border-b border-gray-200">
                    <a href="{{route('admin.products')}}" class="transition-colors duration-300 text-xs font-semibold bg-gray-200 hover:bg-gray-300 rounded-full py-2 px-8"> < {{__('app.back')}} </a>
                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/admin/product/list.blade.php
<x-app-layout>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                            <a href="{{route('product.create')}}" class="text-indigo-600 hover:text-indigo-900">{{ __('app.create_pr') }}</a>
                        </td>
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200">
                                <thead class="bg-gray-50">
                                <tr>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        {{ __('app.id') }}
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        {{ __('app.name') }}
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        {{ __('app.category') }}
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        {{ __('app.description') }}
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        {{ __('app.img') }}
                                    </th>
                                    <th scope="col" class="relative px-6 py-3">
                                    </th>
                                    <th scope="col" class="relative px-6 py-3">
                                    </th>
                                </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                @foreach($products as $product)
                                <tr>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        {!! $product->id !!}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        {!! substr($product->name,0,30) !!}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        {!! $product->category->name??"" !!}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {!! substr($product->description,0,40) !!}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        <img src="{{ asset('storage/' . $product->img) }}" alt="not found image" width="100"/>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{{route('product.edit',$product->id)}}" class="text-indigo-600 hover:text-indigo-900">{{ __('app.edit') }}</a>
                                    </td>
                                    {{ Form::open((['url' => route('product.destroy',$product->id),'method'=>'DELETE'])) }}

                                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                            {{Form::submit( __('app.delete') ,['class'=>'text-indigo-600 hover:text-indigo-900'])}}
                                        </td>

                                    {{ Form::close() }}
                                </tr>
                                @endforeach
                                <!-- More people... -->
                                </tbody>
                            </table>
                        </div>
                    </div>
                    {!! $products->links() !!}
                </div>
            </div>
        </div>
    </div>




</x-app-layout>